import dns from "node:dns";
dns.setServers(['8.8.8.8','8.8.4.4'])

import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const roboto = Roboto_Slab({
  variable: "--roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` h-full antialiased`}
    >
      <body className={`${roboto.className}`}>
        <Navbar/>
        <ToastContainer />
        {children}
        <Footer/>
        </body>
    </html>
  );
}
