import { Geist, Geist_Mono, Roboto_Condensed, Roboto_Slab } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const roboto = Roboto_Slab({
  variable: "--roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className={`${roboto.className}`}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
